spring:
  application:
    name: eureka-service # ==> This is Service-Id  
  profiles: eureka-north-india
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true 
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/,http://eureka-south-india:7002/eureka/,http://eureka-west-india:7004/eureka/,http://eureka-east-india:7003/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    
  instance:
    hostname: eureka-north-india
    appname: eureka-cluster
    
server:
  port: 7001
  
management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
      
      
---

spring:
  application:
    name: eureka-service # ==> This is Service-Id  
  profiles: eureka-south-india
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true #dont register this service with registry
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/,http://eureka-north-india:7001/eureka/,http://eureka-west-india:7004/eureka/,http://eureka-east-india:7003/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
  
  instance:
    hostname: eureka-south-india
    appname: eureka-cluster
    
    
server:
  port: 7002
  
  
management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true

  
---

spring:
  application:
    name: eureka-service # ==> This is Service-Id  
  profiles: eureka-east-india
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true #dont register this service with registry
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/,http://eureka-south-india:7002/eureka/,http://eureka-west-india:7004/eureka/,http://eureka-north-india:7001/eureka/  
  server:
    wait-time-in-ms-when-sync-empty: 0
    
  instance:
    hostname: eureka-east-india
    appname: eureka-cluster
    
    
server:
  port: 7003
  
management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true  
  
---

spring:
  application:
    name: eureka-service # ==> This is Service-Id  
  profiles: eureka-west-india
  
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true #dont register this service with registry
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/,http://eureka-south-india:7002/eureka/,http://eureka-north-india:7001/eureka/,http://eureka-east-india:7003/eureka/ 
  server:
    wait-time-in-ms-when-sync-empty: 0
    
  instance:
    hostname: eureka-west-india
    appname: eureka-cluster
    
    
server:
  port: 7004
  
  
management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true